export const TABLE_HEADERS = {
	PENDING: [
		'contract',
		'shipmentMonth',
		'originPort',
		'ico',
		'secondary_ico_id',
		'mark',
		'quality',
		'units',
		'packaging',
		'customer',
		'destinationPort',
		'sample',
		'incoterm',
		'price_type',
		'production_order',
		'milling_order',
		'milling_state',
		'weight',
	],
	EXPORTED: [
		'contract',
		'shipmentMonth',
		'originPort',
		'ico',
		'secondary_ico_id',
		'mark',
		'quality',
		'units',
		'packaging',
		'customer',
		'destinationPort',
		'sample',
		'incoterm',
		'price_type',
		'production_order',
		'milling_order',
		'milling_state',
		'weight',
		'comments',
	],
	VIEW: [
		'contract',
		'shipmentMonth',
		'originPort',
		'ico',
		'secondary_ico_id',
		'mark',
		'quality',
		'units',
		'packaging',
		'customer',
		'destinationPort',
		'sample',
		'incoterm',
		'price_type',
		'production_order',
		'milling_order',
		'milling_state',
		'weight',
		'comments',
	],
	CREATE_CONTAINER: [
		'ico_id',
		'secondary_ico_id',
		'originPort',
		'contract',
		'customer',
		'mark',
		'units',
		'packaging_capacity',
		'quality',
		'sample',
		'shipmentMonth',
		'destinationPort',
		'price_type',
		'production_order',
		'milling_order',
		'milling_state',
		'weight',
		'select',
	],
	EDIT_CONTAINER: [
		'shipmentMonth',
		'originPort',
		'ico_id',
		'secondary_ico_id',
		'mark',
		'units',
		'quality',
		'packaging_capacity',
		'sample',
		'destinationPort',
		'price_type',
		'production_order',
		'milling_order',
		'milling_state',
		'weight',
		'select',
	],
	ANNOUNCEMENTS: [
		'ico',
		'date_landing',
		'units',
		'packaging_capacity',
		'lot_type',
		'origin_port',
		'estimated_kg',
		'announcement',
		'allocation',
		'sales_code',
		'revision_number',
	],
	MANAGE_USERS: ['username', 'role.name', 'actions'],
};

// Individual exports for backward compatibility
export const headersTablePending = TABLE_HEADERS.PENDING;
export const headersTableExported = TABLE_HEADERS.EXPORTED;
export const headersTableView = TABLE_HEADERS.VIEW;
export const headersTableCreateContainer = TABLE_HEADERS.CREATE_CONTAINER;
export const headersTableEditContainer = TABLE_HEADERS.EDIT_CONTAINER;
export const headersTableManageUsers = TABLE_HEADERS.MANAGE_USERS;
